# Generated by Django 2.1.5 on 2022-01-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esami_sostenuti_e_relativi_esiti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sessione', models.CharField(blank=True, max_length=255, null=True)),
                ('Data', models.DateField(blank=True)),
                ('Esame', models.CharField(blank=True, max_length=255, null=True)),
                ('Centro', models.CharField(blank=True, max_length=255, null=True)),
                ('Parte', models.CharField(blank=True, max_length=255, null=True)),
                ('Esito', models.CharField(blank=True, max_length=255, null=True)),
                ('Note_appello', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Esami sostenuti e relativi esiti',
            },
        ),
        migrations.CreateModel(
            name='Verifica_Risultati_Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MATRICOLA', models.IntegerField()),
                ('COGNOME', models.CharField(blank=True, max_length=255, null=True)),
                ('NOME', models.CharField(blank=True, max_length=255, null=True)),
                ('DATA_DI_NASCITA', models.DateField(blank=True)),
                ('NAZIONALITA', models.CharField(blank=True, max_length=255, null=True)),
                ('Auto_QR_Code', models.ImageField(blank=True, help_text='Auto Generate QR Code', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Verifica Risultati Candidato',
            },
        ),
    ]
