# Generated by Django 2.1.5 on 2022-01-21 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifica_risultati_candidato',
            name='DATA_DI_NASCITA',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 22, 1, 22, 39, 707369)),
        ),
    ]
